In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

code for the task : https://judge.nitro-ai.org/competitions/roai-2025/baraj-nationala-2026/1/view (though this task is a no object detection task but just doing object detection here for the sake of practice)

In [2]:
train_ds = pd.read_csv("/kaggle/input/datasets/murtazaabdullah2010/professor-grammar-vs-the-box-avalanche/train_data(1)/train/train.csv")
test_ds = pd.read_csv("/kaggle/input/datasets/murtazaabdullah2010/professor-grammar-vs-the-box-avalanche/test_data(1)/test/test.csv")
sample_sub = pd.read_csv("/kaggle/input/datasets/murtazaabdullah2010/professor-grammar-vs-the-box-avalanche/sample_output(3).csv")
train_imgs= "/kaggle/input/datasets/murtazaabdullah2010/professor-grammar-vs-the-box-avalanche/train_data(1)/train/images/"
test_imgs = "/kaggle/input/datasets/murtazaabdullah2010/professor-grammar-vs-the-box-avalanche/test_data(1)/test/images/"

In [3]:
train_ds

,filename,pred_boxes,pred_scores,gt_boxes
0,FudanPed00001.png,"[[419.68597412109375, 170.06802368164062, 536....","[0.9997385144233704, 0.9995905756950378]","[[159.0, 181.0, 301.0, 430.0], [419.0, 170.0, ..."
1,FudanPed00002.png,"[[67.23969268798828, 91.85848999023438, 188.70...","[0.9994507431983948, 0.9952310919761658, 0.276...","[[67.0, 92.0, 190.0, 379.0]]"
2,FudanPed00003.png,"[[285.0282287597656, 129.271484375, 443.854888...","[0.9997422099113464, 0.6000857353210449, 0.310...","[[292.0, 134.0, 446.0, 420.0]]"
3,FudanPed00005.png,"[[180.94015502929688, 54.6724853515625, 318.92...","[0.9991474151611328, 0.9936768412590027, 0.931...","[[187.0, 58.0, 319.0, 335.0], [1.0, 52.0, 39.0..."
4,FudanPed00006.png,"[[204.8242645263672, 95.5763168334961, 349.535...","[0.9995357990264893, 0.9956884980201721, 0.981...","[[207.0, 107.0, 345.0, 384.0], [1.0, 107.0, 86..."
...,...,...,...,...
97,PennPed00090.png,"[[202.40769958496094, 42.43639373779297, 362.9...","[0.9993163347244263, 0.9981517195701599, 0.938...","[[81.0, 22.0, 211.0, 357.0], [42.0, 38.0, 121...."
98,PennPed00091.png,"[[209.3085174560547, 21.3303165435791, 345.129...","[0.9985675811767578, 0.8963249921798706, 0.326...","[[211.0, 25.0, 335.0, 320.0]]"
99,PennPed00092.png,"[[288.2504577636719, 98.82373809814453, 460.28...","[0.9989018440246582, 0.9987700581550598, 0.945...","[[105.0, 75.0, 310.0, 433.0], [287.0, 93.0, 46..."
100,PennPed00093.png,"[[44.70914840698242, 9.522002220153809, 226.76...","[0.9976614713668823, 0.8436945080757141, 0.215...","[[50.0, 5.0, 221.0, 301.0]]"
101,PennPed00094.png,"[[127.94134521484375, 24.262332916259766, 256....","[0.9995937943458557, 0.05585489422082901]","[[121.0, 26.0, 255.0, 321.0]]"

In [4]:
test_ds

,datapointID,filename,pred_boxes,pred_scores
0,0,FudanPed00004.png,"[[163.44219970703125, 56.78453826904297, 332.4...","[0.9995136260986328, 0.9963480830192566, 0.719..."
1,1,FudanPed00007.png,"[[112.57318878173828, 66.12821197509766, 218.9...","[0.9996175765991211, 0.9995394945144653, 0.999..."
2,2,FudanPed00015.png,"[[27.121030807495117, 40.49905014038086, 170.6...","[0.9994598031044006, 0.9975029826164246, 0.990..."
3,3,FudanPed00018.png,"[[11.608231544494629, 14.169098854064941, 119....","[0.99934321641922, 0.3925949037075043, 0.09361..."
4,4,FudanPed00020.png,"[[335.6383972167969, 95.13361358642578, 508.55...",[0.9998922348022461]
...,...,...,...,...
63,63,PennPed00085.png,"[[240.2248992919922, 33.98091125488281, 378.36...","[0.9989711046218872, 0.9985439777374268, 0.465..."
64,64,PennPed00088.png,"[[78.45006561279297, 20.069250106811523, 218.3...",[0.9997559189796448]
65,65,PennPed00089.png,"[[83.2823715209961, 18.993953704833984, 170.43...","[0.999527096748352, 0.999445378780365, 0.21825..."
66,66,PennPed00095.png,"[[314.3113708496094, 58.43041229248047, 431.06...","[0.9998408555984497, 0.9995632767677307, 0.838..."
67,67,PennPed00096.png,"[[99.97357177734375, 21.904281616210938, 210.7...","[0.9996668100357056, 0.9996445178985596, 0.938..."

In [5]:
import ast
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from torchvision.models import resnet18, resnet34, resnet50
import json
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.ops import box_iou

In [6]:
def nms(boxes, confs):
    boxes = ast.literal_eval(scores)
    confs= ast.literal_eval(confs)
    sorted_ = sorted(zip(boxes, confs), key=lambda x: x[1], reverse=True)
    boxes, confs = zip(*sorted_)
    boxes = list(boxes)
    confs = list(confs)
    keep =[]
    remove = set()
    for i in range(len(boxes)):
        if i in remove:
            continue
        for j in range(i+1, len(boxes)):
            b = boxes[j]
            if j in removed:
                continue
            iou= box_iou(box[i], box[j])
            if iou >0.5:
                remove.add(j)
    return [boxes[i] for i in keep]

In [8]:
from PIL import Image
class DF(Dataset):
    def __init__(self, df, path, trans=None,is_test=False):
        self.df = df
        self.path = path
        self.trans = trans
        self.is_test = is_test
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        img_path = os.path.join(self.path, self.df["filename"][idx])
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        x_scale = 224 / w
        y_scale = 224 / h
        img = self.trans(img)
        if self.is_test:
            return img
        boxes = ast.literal_eval(self.df["gt_boxes"][idx])
        boxes = torch.tensor(boxes, dtype=torch.float32)
        boxes[:, [0, 2]] *= x_scale
        boxes[:, [1, 3]] *= y_scale
        labels = torch.ones((boxes.shape[0],), dtype=torch.int64)
        target = {
            "boxes": boxes,
            "labels": labels,
            "image_id": torch.tensor([idx])
        }
        return img, target

from torchvision import transforms as T
train_trans = T.Compose([
    T.Resize((224, 224)),
    T.ColorJitter(0.2, 0.2, 0.2, 0.4),
    T.GaussianBlur((3, 3)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
test_trans = T.Compose([
    T.Resize((224, 224)),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
def collate_fn(batch):
    return tuple(zip(*batch))
train_df= DF(train_ds, train_imgs, trans = train_trans, is_test= False)
test_df= DF(train_ds, train_imgs, trans = test_trans, is_test= True)
train_dl = DataLoader(train_df,batch_size=16,shuffle=True,num_workers=4,pin_memory=True,collate_fn=collate_fn)
test_dl = DataLoader(test_df,batch_size=16,shuffle=False,num_workers=4,pin_memory=True,collate_fn=collate_fn)
device = ("cuda" if torch.cuda.is_available() else "cpu")

In [9]:
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
class MODEL(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = fasterrcnn_resnet50_fpn(weights="DEFAULT")
        inf = self.model.roi_heads.box_predictor.cls_score.in_features
        self.model.roi_heads.box_predictor = FastRCNNPredictor(inf,2)
    def forward(self, x, y=None):
        return self.model(x, y)

model = MODEL().to(device)

Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /root/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth

100%|██████████| 160M/160M [00:00<00:00, 172MB/s]

In [ ]:
opt = torch.optim.AdamW(model.parameters(), lr = 1e-4, weight_decay= 2e-4)
for e in range(10):
    t_loss = 0
    model.train()
    for xs, ys in train_dl:
        xs = [x.to(device) for x in xs]
        ys = [{k: v.to(device) for k, v in y.items()} for y in ys]
        ld = model(xs, ys)
        loss = sum(loss for loss in ld.values())
        t_loss += loss.item()
        opt.zero_grad()
        loss.backward()
        opt.step()

In [ ]:
test_preds = []
model.eval()
with torch.no_grad():
    for batch in test_dl:
        xs = list(x.to(device) for x in batch)
        out = model(xs)   
        test_preds.extend(out)
test_preds= np.concatenate(test_preds, axis  = 1)
len(test_preds), len(test_df)

In [ ]:
boxes = []
for idx, row in test_ds.iterrows():
    box = nps(row["pred_boxes"], row["pred_scores"])
    boxes.append(box)
sub1 = pd.DataFrame({
    "subtaskID": 1, 
    "datapointID": test_ds["datapointID"], 
    "answer": boxes
})
boxes = []
for t in test_preds:
    boxes.append(nms())